### PR TITLE
Add fixed size array support

### PR DESCRIPTION
**Pull request by prescientmoon**
This is a basic fix to #9 . I can make any changes necessary to get this in!

### CODE REVIEW

**Comment by EnderShadow8** [comment]
Just to clarify, what `arrayOf(x)` does is create a component store where the data for entity `n` is stored in the slice (n*x, (n+1)*x]

Is this correct?

**Comment by Mateiadrielrafael** [comment]
Yeah, that was my intention. Is there a better way to do it?

**Comment by EnderShadow8** [comment]
The way bitECS does this is to create a regular array of TypedArrays, so that `arr[n]` is a TypedArray corresponding to entity n's array data. It's possible to do this already using `types.custom(() => Float32Array(x))` to get a component whose datatype is an array of `x` floats.

**Comment by Mateiadrielrafael** [comment]
We could also consider creating an es6 proxy to overload the indexing operation

**Comment by EnderShadow8** [comment]
Proxies are quite slow, at least they were the last time I checked. That would nullify most of the advantages of using TypedArrays in the first place over regular JS objects.

**Pull request closed without merging**
